import Head from "next/head";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import Carousel from "nuka-carousel";
import Image from "next/image";
import DatePickerComponent from "@/components/datepiker";
import Header from "./header";
import Footer from "./footer";
import Tourlist from "@/components/tours";
import * as React from "react";
import Stack from "@mui/material/Stack";
import Button from "@mui/material/Button";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main id="top" data-spy="scroll" data-target=".navbar" data-offset="260">
        <Header />

        {/* <!-- Teaser start --> */}
        <section id="teaser">
          <div className="container">
            <div className="row">
              <div className="col-md-7 col-xs-12 pull-right">
                <div className="carousel">
                  <div className="carousel-inner">
                    <Carousel
                      renderCenterLeftControls={({ previousSlide }) => (
                        <button onClick={previousSlide}>
                          <span className="glyphicon glyphicon-chevron-left"></span>
                        </button>
                      )}
                      renderCenterRightControls={({ nextSlide }) => (
                        <button onClick={nextSlide}>
                          <span className="glyphicon glyphicon-chevron-right"></span>
                        </button>
                      )}
                    >
                      <Image
                        src="/img/car1.png"
                        alt="car1"
                        width={590}
                        height={325}
                      />
                      <Image
                        src="/img/car2.png"
                        alt="car2"
                        width={590}
                        height={325}
                      />
                    </Carousel>
                  </div>
                </div>
              </div>
              <div className="col-md-5 col-xs-12 pull-left">
                <div className="reservation-form-shadow">
                  <Stack spacing={2} direction="row">
                    <Button
                      style={{ color: "black", fontSize: "1em" }}
                      variant="outlined"
                    >
                      Tours
                    </Button>
                  </Stack>
                  <form
                    style={{ paddingTop: "0em" }}
                    action="#"
                    method="post"
                    name="car-select-form"
                    id="car-select-form"
                  >
                    <h3 style={{ textAlign: "center" }}>List of places</h3>
                    {/* <!-- Pick-up date/time start --> */}
                    {/* <DatePickerComponent /> */}

                    <Tourlist />

                    <input
                      type="submit"
                      className="submit"
                      name="submit"
                      value="continue car reservation"
                      id="checkoutModalLabel"
                    />
                  </form>
                </div>
              </div>
            </div>
          </div>
        </section>
        <div className="arrow-down"></div>
        {/* <!-- Teaser end --> */}

        {/* <!-- Services start --> */}
        <section id="services" className="container">
          <div className="row">
            <div className="col-md-12 title">
              <h2>Customer Services</h2>
              <span className="underline">&nbsp;</span>
            </div>

            {/* <!-- Service Box start --> */}
            <div className="col-md-6">
              <div className="service-box wow fadeInLeft" data-wow-offset="100">
                <div className="service-icon">+</div>
                <h3 className="service-title">Special rates on car booking</h3>
                <div className="clearfix"></div>
                <p className="service-content">
                  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed
                  nonumy eirmod tempor invidunt ut labore et dolore magnaed
                  aliquyam erat, sed diam voluptua. At vero eos et accusam et
                  justo duo dolores et ea rebum. Stet clita kasd gubergren.
                </p>
              </div>
            </div>
            {/* <!-- Service Box end --> */}

            {/* <!-- Service Box start --> */}
            <div className="col-md-6">
              <div
                className="service-box wow fadeInRight"
                data-wow-offset="100"
              >
                <div className="service-icon">+</div>
                <h3 className="service-title">Mobile Phone Reservation</h3>
                <div className="clearfix"></div>
                <p className="service-content">
                  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed
                  nonumy eirmod tempor invidunt ut labore et dolore magnaed
                  aliquyam erat, sed diam voluptua. At vero eos et accusam et
                  justo duo dolores et ea rebum. Stet clita kasd gubergren.
                </p>
              </div>
            </div>
            {/* <!-- Service Box end -->

				<!-- Service Box start --> */}
            <div className="col-md-6">
              <div className="service-box wow fadeInLeft" data-wow-offset="100">
                <div className="service-icon">+</div>
                <h3 className="service-title">Unlimited Miles Car Rental</h3>
                <div className="clearfix"></div>
                <p className="service-content">
                  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed
                  nonumy eirmod tempor invidunt ut labore et dolore magnaed
                  aliquyam erat, sed diam voluptua. At vero eos et accusam et
                  justo duo dolores et ea rebum. Stet clita kasd gubergren.
                </p>
              </div>
            </div>
            {/* <!-- Service Box end -->

				<!-- Service Box start --> */}
            <div className="col-md-6">
              <div
                className="service-box wow fadeInRight"
                data-wow-offset="100"
              >
                <div className="service-icon">+</div>
                <h3 className="service-title">One Way Car Rentals</h3>
                <div className="clearfix"></div>
                <p className="service-content">
                  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed
                  nonumy eirmod tempor invidunt ut labore et dolore magnaed
                  aliquyam erat, sed diam voluptua. At vero eos et accusam et
                  justo duo dolores et ea rebum. Stet clita kasd gubergren.
                </p>
              </div>
            </div>
            {/* <!-- Service Box end --> */}
          </div>
        </section>
        {/* <!-- Services end --> */}
        {/* <!-- Reviews start --> */}
        <section id="reviews" className="container wow fadeInUp">
          <div className="row text-center">
            <div className="col-md-12 stars">
              <span className="glyphicon glyphicon-star"></span>
              <span className="glyphicon glyphicon-star"></span>
              <span className="glyphicon glyphicon-star big"></span>
              <span className="glyphicon glyphicon-star"></span>
              <span className="glyphicon glyphicon-star"></span>
            </div>
            <div className="col-md-10 col-md-offset-1">
              <div
                id="reviews-carousel"
                className="carousel slide carousel-fade"
                data-ride="carousel"
              >
                <div className="carousel-inner">
                  {/* <!-- Review item 1 start --> */}
                  <div className="item active">
                    <div className="review">
                      It is always a positive experience when renting from your
                      5th street location. The staff is very professional and
                      efficient and always smiling. And I always feel welcome
                      and appreciated. The management is always prompt to solve
                      any issue at any moment. Their efficiency and
                      professionalism makes it my number one choice.
                    </div>
                    <div className="author">
                      – Michael Smith, Santa Barbara CA
                    </div>
                  </div>
                  {/* <!-- Review item 1 end -->

							<!-- Review item 2 start --> */}
                  <div className="item">
                    <div className="review">
                      This rental was the best rental experience ever! After
                      completing all details on-line myself, the pick-up was
                      super efficient, extremely friendly, and free of the usual
                      5 - 10 min very unpleasant drilling of why one is not
                      signing up to all options (insurance, etc). I was handed
                      the keys and a wide register print out that required...
                    </div>
                    <div className="author">– Jon Doe, Las Vegas NV</div>
                  </div>
                  {/* <!-- Review item 2 end -->

							<!-- Review item 3 start --> */}
                  <div className="item">
                    <div className="review">
                      This was my first time renting from car|rental. And over
                      all it was a wonderful experience I have no complaints.
                      The service rep help me find the best rental to suit my
                      needs. I also love the fact that you guys provide luxury
                      rentals at a great price. I will definitely rent with this
                      company again.
                    </div>
                    <div className="author">
                      – Michael Smith, Santa Barbara CA
                    </div>
                  </div>
                  {/* <!-- Review item 3 end --> */}
                </div>

                {/* <!-- Review Nav start --> */}
                <ol className="carousel-indicators">
                  <li
                    data-target="#reviews-carousel"
                    data-slide-to="0"
                    className="active"
                  ></li>
                  <li data-target="#reviews-carousel" data-slide-to="1"></li>
                  <li data-target="#reviews-carousel" data-slide-to="2"></li>
                </ol>
                {/* <!-- Review Nav end --> */}
              </div>
            </div>
          </div>
        </section>
        {/* <!-- Reviews end --> */}
      </main>
      <Footer />
    </>
  );
}
